volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.0-alpine
    container_name: foodgram_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env
  
  backend:
    image: nikkurkov/foodgram_backend:latest
    container_name: foodgram_backend
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    env_file: .env

  frontend:
    image: nikkurkov/foodgram_frontend:latest
    container_name: foodgram_frontend
    # Кладем build фронта в общий том static
    command: >
      sh -c "
        mkdir -p /app/static &&
        rm -f /app/static/index.html /app/static/manifest.json /app/static/favicon.ico &&
        rm -rf /app/static/static &&
        cp -rf /app/build/* /app/static/
      "
    volumes:
      - static:/app/static/
    restart: "no"


  nginx:
    image: nikkurkov/foodgram_gateway:latest
    container_name: foodgram_nginx
    ports:
      - "80:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
      - frontend
    restart: always
